Add common films
Remsely/java-filmorate pull request #11
Opened 2024-04-02 22:26 UTC by 4IPE

2024-04-03 10:40 UTC, Remsely requested changes

2024-04-03 10:40 UTC, Remsely commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getCommonFilms(@RequestParam(value = "userId", required = false) long userId, @RequestParam(value = "friendId", required = false) long friendId) {
Не совсем понимаю, зачем здесь `required = false`. Параметры `userId` и `friendId` обязательные. Если мы сделаем запрос по `films/common` без параметров, то получим `500 (internal server error)` вместо `400 (bad request)`.
Также небольшая помарка по code style - слишком длинная строка.

2024-04-03 10:40 UTC, Remsely commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getCommonFilm(long userId, long friendId) {
Это, вроде как, более оптимально делать одним sql-запросом, но я в этом не уверен) У нас есть эксперт по SQL, дождемся его ревью.

2024-04-03 11:35 UTC, Remsely reviewed
Вижу правки, ждем еще 1 ревьювера)

2024-04-03 11:36 UTC, Remsely approved these changes

2024-04-04 07:30 UTC, KoryRunoMain approved these changes

2024-04-04 07:34 UTC, merged